---
# Usage: http://ruhoh.com

# This helps parsers (and hosting platforms) determine which version is needed to compile your site.
# If you compile your blog yourself, setting this won't matter, but it's a nice thing to keep updated.
RuhohSpec: "2.3"

# Used for things like RSS that need the full URL to a given resource.
# This DOES NOT affect any of your paths or links in any way.
# This DOES NOT configure domain mapping. See post2.ruhoh.com for hosting options.
production_url: "http://dourok.info"

# Intelligently prepends all urls in the system with the given base_path.
# This allows you to host your blog in a subdirectory of a given website.
# Example:
#  To host at the path: http://myuniversity.edu/staff/me/~/blog.
#  set base_path: "/staff/me/~/blog"
# NOTE: base_path is never added in development mode (for convenience).
base_path: "/"

# Tell ruhoh which folder will model the "theme"
twitter :
  # Tells ruhoh which collection class to use for this folder.
  # Here we use "theme" which makes this folder the theme.
  use : "ignore"

moon :
  use : "theme"

_root:
  summary_lines: 20
  rss:
    enable: false
  paginator:
    enable: false
    
posts:
  sort: ["date", "desc"]
  permalink: /:year/:month/:day/:filename/
  summary_lines: 7
  latest: 10
  rss:
    enable: true
    limit: 10
    # The url to prepend to the rss.xml feed, e.g.: /posts/rss.xml
    # Defaults to: "/<resource_name>/"
    # Always start with a forward slash, as ruhoh will internally respect any base_path you set.
    url: "/"
  paginator:
    enable: false
    # The url your paginated pages will be located: e.g /posts/index/1, /posts/index/2, /posts/index/3
    # Always start with a forward slash, as ruhoh will internally respect any base_path you set.
    url: "/posts/index/"
    per_page: 5
    # Set the custom page you want page#1 of your posts paginator to link to. (default: /posts/index/1)
    # Note the default is technically <paginator.url>/1 just as the other paginated pages.
    # It is up to you to display the paginator_pagination links somewhere in this case.
    #
    # root_page has been set to the root for a more traditional style blog feel.
    root_page: '/'

# Enable the asset pipeline to process stylesheets and javascripts using sass, coffeescript, etc.
# The asset pipeline supports live preview + bundling/minification on compile.
# Sprockets is used for the ruby version: https://github.com/sstephenson/sprockets#readme
#
# To Enable:
#   1. Set enable to true.
#   2. Update Gemfile to include the sprockets and supporting processor gems.
#
# It's done this way because some users just want to write a freaking blog post
# and have no need for a billion gems -- hopefully you agree with me =)
asset_pipeline:
  enable: false

widgets :

  analytics :
    use : google
    # -- config for google --
    tracking_id : 'UA-12243999-3'

    # -- config for getclicky  --
    # site_id :

  comments :
    use : my_disqus
    enable : true
    # -- config for disqus --
    short_name : doousblog # Change This!

    # -- config for livefyre --
    # site_id : 123

    # -- config for intensedebate --
    # account : 123abc

    # -- config for facebook --
    # appid : 123
    # num_posts: 5
    # width: 580
    # colorscheme: light

  google_prettify :
    use : static_file
   
  gplus :
     enable : true
    
  jiathis :
     enable : true
     uid : 1677096
    
  math :
     enable : false
     
  processing_js‎ : 
     enable : false

# ignore

img :
  use : "ignore"

images :
  use : "ignore"

tools :
  use : "ignore"

# ignore tmp folder in server
tmp :
  use : "ignore"

notes :
   paginator:
    enable: false
   default_dir: "Other/Misc"  # 设置笔记默认路径
   quick_title: "%Y年%m月%d日杂记" # 快捷笔记的标题，为空的时候没标题
   quick_name: "note-%Y-%m-%d"  # 快捷笔记的文件名
   quick_dir: "%Y/%m" # 快捷笔记按月分类的路径，归属到 default_dir
   