---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : moon
production_url : http://brain.dourok.info

posts:
  permalink: /:year/:month/:day/:filename/
  summary_lines: 7
  latest: 10

pages:
  permalink: 'pretty'