---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : moon
production_url : http://douo.ruhoh.com

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'