---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '2.0.alpha'

production_url : http://dourok.info

theme:
  name: 'moon'

posts:
  permalink: /:year/:month/:day/:filename/
  summary_lines: 7
  latest: 10

pages:
  permalink: 'pretty'