---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '2.0.alpha'

production_url : http://dourok.info

theme:
  name: 'moon'

posts:
  permalink: /:year/:month/:day/:filename/
  summary_lines: 7
  latest: 10

paginator:
  enable: false

pages:
  permalink: 'pretty'

diary:
  url: 'diary'

notes:
  url: /notes
  index: index.md
  tag_url: /notes/tags
  default: misc

toc:
  friendly_anchor: true  # convertor 不能再如配置,暂时没用