title : DouO's Blog
tagline: 有時樹會倒下，某片天頃刻明亮
author :
  name : DouO
  email : dourokinga@gmail.com
  github : douo
  twitter : dourok
  feedburner : douo

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

# 自己重新實現的導航
nav :
  - title: home
    url: /
    describe: 主頁
  - title: archives
    url: /archives
    describe: 歸檔
  - title: wiki
    url: http://wiki.dourok.info
    describe: 我的個人筆記
  - title: feed
    url: /rss.xml
    describe: 訂閱
  - title: about
    url: /about
    describe: 關於我
      
links:
  - title: MAGICALBOY
    url: http://magicalboy.com/
  - title: 驴子博客
    url: http://www.cnlvzi.com/

note:
  title:  DouO's Note
  url: /notes