title : DouO's Blog
tagline: 有時樹會倒下，某片天頃刻明亮
author :
  name : Tiou Lims
  email : dourokinga@gmail.com
  github : douo
  twitter : dourok
  feedburner : douo

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
