name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: SSH connection to Actions
      uses: p3terx/debugger-action@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        pwd
